services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

  mysql:
    image: mysql:8.0
    container_name: axiom-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: axiom_development
    ports:
      - "3307:3306"
    volumes:
      - ~/works/docker/axiom_mysql:/var/lib/mysql

volumes:
  redis_data:
